### ISSUE TITLE
Add support for new URP version  17.0

### ISSUE THREAD

**Issue by AvatarisAI** [soupday/cc_unity_tools_URP#51]
Character shaders pink in webgl build, if used CC/iC Unity Tools 1.5.2 URP15 package. 
![image](https://github.com/soupday/cc_unity_tools_URP/assets/143421243/bac71436-d0b2-413f-96ef-da990ad9b2e4)

**Comment by slimshady1281** [comment]
@AvatarisAI  were you able to make it work with a lower version ?

@soupday Is there a lower version we can use temporarily for webgl

**Comment by soupday** [comment]
It might be the minimum shader model. URP15 sets it quite high to support all the new lighting features. The Amplify shaders are all compiled to this minimum level. 

You could try turning off the Amplify shaders:

![noamp](https://github.com/soupday/cc_unity_tools_URP/assets/79094830/72bca08c-313e-4ddf-8a26-97f858992ac6)

This will force it to use the simpler but more compliant URP Shader Graph based shaders, WebGL _shouldn't_ have any issue with that. I left this in as an option in case certain build platforms didn't like the more custom shaders.
